### ISSUE TITLE
IP Address Decode Out of Bounds Exception

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#1040]
### Describe the bug

I was looking at a log from QNS ([here](https://interop.seemann.io/logs/2020-11-17T08:02/quiche_msquic/handshakecorruption/client/quic.log)) and saw this exception:

```
Invalid TraceLine : timestamp = 08:43:01.967155519, delta = +0.000022000, trace:hostname = client, name = CLOG_DATAPATH_LINUX_C:DatapathCreated, stream.packet.context = { cpu_id = 0 }, stream.event.context = { vpid = 95, vtid = 100 }, event.fields = { arg2 = 0x7F8F48002290, arg3_len = 0, _arg3_length = 0, arg3 = [ ], arg4_len = 28, _arg4_length = 28, arg4 = [ [0] = 2, [1] = 0, [2] = 1, [3] = -69, [4] = -63, [5] = -89, [6] = 100, [7] = 100, [8] = 0, [9] = 0, [10] = 0, [11] = 0, [12] = 0, [13] = 0, [14] = 0, [15] = 0, [16] = 0, [17] = 0, [18] = 0, [19] = 0, [20] = 0, [21] = 0, [22] = 0, [23] = 0, [24] = 0, [25] = 0, [26] = 0, [27] = 0 ] } System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at msquic.clog_config.Types.ADDR(Byte[] value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at clog2text_lttng.CLogCustomTraceEmittorFactory.Decode(CLogEncodingCLogTypeSearch type, IClogEventArg value, CLogLineMatch traceLine, String& decodedValue) in /home/vsts/work/1/s/src/clogutils/CLogCustomTraceEmittorFactory.cs:line 159
   at clogutils.ConfigFile.CLogConfigurationFile.DecodeUsingCustomDecoder(CLogEncodingCLogTypeSearch node, IClogEventArg value, CLogLineMatch traceLine, String& decodedValue) in /home/vsts/work/1/s/src/clogutils/ConfigFile/CLogConfigurationFile.cs:line 228
   at clogutils.CLogConsoleTrace.DecodeAndTraceToConsole(StreamWriter outputfile, CLogDecodedTraceLine bundle, String errorLine, CLogConfigurationFile config, Dictionary`2 valueBag, EventInformation eventInfo, Boolean showTimeStamp, Boolean showCPUInfo) in /home/vsts/work/1/s/src/clogutils/CLogConsoleTrace.cs:line 89
```

### Expected vs actual behavior

We obviously shouldn't be throwing any exceptions when trying to decode traces. It likely a bug in the decode code.

**Comment by ThadHouse** [comment]
This should probably involve both a fix on our end and a fix on clogs end to not propogate these errors. Will look when back.

**Comment by ThadHouse** [comment]
Actually, double checking through this no need for a fix on clogs side. When I was just skimming through, I assumed this was just crashing the log completely. Since it keeps going, clog is doing what I'd expect. Just need to fix the decode code then, which I'll dig into.
