### ISSUE TITLE
Cannot connect via IPv4 when listener binds on IPv6

### ISSUE THREAD

**Issue by rzikm** [microsoft/msquic#2704]
### Describe the bug

Discovered when investigating https://github.com/dotnet/runtime/issues/67442.

For purposes of an HTTP3 servers, we want to listen to all connections from any IP, which makes the server listen on an IPv6 "AnyAddress" and configure the socket such that it also receives IPv4 traffic (via mapped IPs).

Debugging shows that while MsQuic receives UDP datagrams sent using IPv4 addresses, the datagram will not get matched to any existing listener and the connection will get immediately closed with a TLS alert corresponding to a failed ALPN negotiation.

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [X] Debian
- [ ] Other (specify below)

### Additional OS information

Reproduced on Linux, haven't tried reproducing on Windows.

### MsQuic version

main

### Steps taken to reproduce bug

1. Create a server that listens on an "IPv6 Any" address or IPv6 loopback address
2. Try to connect to the server using its IPv4 Address

The code I used to reproduce can be found at 
https://github.com/dotnet/runtime/tree/main/src/libraries/System.Net.Http/tests/StressTests/HttpStress, but the setup may be a bit complicated:
- Build the .NET runtime (e.g. by running `build.sh -s clr+libs -c Release` in the repo root)
- either install MsQuic globally or put built binaries in `$repoRoot/artifacts/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/`
- run `build-local.sh Release Release` from the directory above
- run both sides of the application:
  - server: `$repoRoot/artifacts/bin/testhost/net7.0-Linux-Release-x64/dotnet ./bin/Release/net7.0/HttpStress.dll -runMode server -http 3.0 -serverUri https://[::1]:5001`
  - client: `$repoRoot/artifacts/bin/testhost/net7.0-Linux-Release-x64/dotnet ./bin/Release/net7.0/HttpStress.dll -runMode server -http 3.0 -serverUri https://127.0.0.1:5001`

### Expected behavior

Connection is established without problems

### Actual outcome

Connection is closed by the server with a TLS alert 120 (failed ALPN negotiation)

**Comment by nibanks** [comment]
Oh, I thought you were saying that if you bound to `[::1]` you incorrectly would get connections from IPv4. It's expected that if you bind to IPv6 Any that you only get IPv6 connections (it's "any IPv6, not any IP"). If you want to have a dual stack listener, you need to bind to any unspecified.

**Comment by nibanks** [comment]
For instance (in native code): https://github.com/microsoft/msquic/blob/main/src/tools/sample/sample.c#L506

**Comment by rzikm** [comment]
I see, thanks for the info, I will try that. In that case the only thing that is weird/confusing is the error code you get in that case, but that seems minor enough.

**Comment by nibanks** [comment]
> when I listen on IPv6Any, I can connect both using IPv4 and IPv6 loopback addresses with TCP

Did you verify this on Windows as well?

cc @maolson-msft would you mind weighing in here, at least in respect to Windows TCP behavior. How does Windows TCP handle dual-stack listeners?

But regardless, the current behavior is by design for MsQuic, and it would be a breaking change to modify it, which will not unless there is an extremely strong reason to do so. Matching a TCP behavior isn't enough.

**Comment by rzikm** [comment]
> Did you verify this on Windows as well?

Only from C# side:

```cs
int port = 5004;

TcpListener listener = new TcpListener(new IPEndPoint(IPAddress.IPv6Any, port));
listener.Start();
Console.WriteLine($"Listening on IPv6Any:{port}");

using TcpClient clientIpv4 = new TcpClient();
var ipv4connect = clientIpv4.ConnectAsync(new IPEndPoint(IPAddress.Loopback, port)).ContinueWith(x =>
{
    Console.WriteLine("Connected via Ipv4 Loopback");
});

using TcpClient clientIpv6 = new TcpClient();
var ipv6connect = clientIpv6.ConnectAsync(new IPEndPoint(IPAddress.IPv6Loopback, port)).ContinueWith(x =>
{
    Console.WriteLine("Connected via Ipv6 Loopback");
});

await Task.WhenAll(ipv4connect, ipv6connect);
```

When run on both Windows or Linux (I tried via WSL2), it produces the same result (both connect)

**Comment by nibanks** [comment]
Are you setting the `IPV6_V6ONLY` socket option?

**Comment by nibanks** [comment]
Then that doesn't make sense to me. That socket option explicitly says that your socket is IPv6 **only**.

**Comment by rzikm** [comment]
I rerun the experiment with plain Sockets and the behavior is the same regardless of the `DualMode` property (although now I notice that with `IPV6_V6Only == 1` it takes slightly longer to connect via IPv4 on Windows).

To not get distracted with this and bring this to some conclusion. From what @nibanks said, the observed MsQuic's behavior is by design and we should use the "unspecified" address family to achieve the desired behavior. In .NET Runtime, we probably want to mimic the TCP behavior, which we can still achieve by special-casing "IPv6 Any" in our MsQuic wrapper.

There is no action on MsQuic team.

Unless there is more to this. I think you can close this issue. Thanks for help!

**Comment by antonfirsov** [comment]
@tmds may also have valuable insights here.

**Comment by nibanks** [comment]
> QUIC is UDP, right?

Yes

> The issue is not so clear to me. If the server responds, it must have received something.
> So why is it considered a socket issue?
> I'm not sure what you mean by 'listener'?

QUIC has bound a wildcard-address, listening UDP socket on the local port. When QUIC receives the datagram from the client, it looks up for a registered QUIC Listener (i.e. app) on the port for a matching address and ALPN. Any mismatch results in the ALPN negotiation failure message being sent out.

> Do you have a 'server' UDP socket that only called bind?

Yes

> And then have 'client' UDP sockets that bind to a local address, with an additional connect to receive from a specific peer?

Client UDP sockets are "connected" to the remote address.

**Comment by tmds** [comment]
I don't understand the issue.

fwiw, DualMode UDP Sockets are working fine on Linux with .NET 6.

```cs
using System.Net;
using System.Net.Sockets;
using System.Text;

Socket receiveSocket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);
receiveSocket.DualMode = true;
receiveSocket.Bind(new IPEndPoint(IPAddress.IPv6Any, 0));
IPAddress ipv4Address = Dns.GetHostAddresses("").First(addr => addr.AddressFamily == AddressFamily.InterNetwork);
int port = (receiveSocket.LocalEndPoint as IPEndPoint)!.Port;

Socket sendSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
sendSocket.Connect(new IPEndPoint(ipv4Address, port));
sendSocket.Send(Encoding.UTF8.GetBytes("Hello"));

byte[] buffer = new byte[1024];
int received = receiveSocket.Receive(buffer);
Console.WriteLine(Encoding.UTF8.GetString(buffer.AsSpan(0, received)));
```

**Comment by nibanks** [comment]
@tmds the question/issue at hand is around the use of the `IPV6_V6ONLY` socket option. I'm getting mixed signals that seem to be saying .NET somehow uses/gets dual-mode sockets without settings `IPV6_V6ONLY` to `FALSE`/`0`. I'm arguing that shouldn't be the case. Without setting that option, the default state for any socket bound to and IPv6 address should only accept IPv6 packets/connections.

**Comment by tmds** [comment]
> Without setting that option, the default state for any socket bound to an IPv6 address should only accept IPv6 packets/connections.

Is `IPV6_V6ONLY = 1` the default on Windows?

On Linux, the default is dual mode.

```
$ cat /proc/sys/net/ipv6/bindv6only
0
```

**Comment by tmds** [comment]
.NET overrides the linux default to match Windows behavior: https://github.com/dotnet/runtime/blob/951df04d97405ff6dd13e708873549fb9acf9a6c/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L68-L80.

And some .NET APIs, in particular: `TcpListener.Create(int port)` and `Socket(SocketType socketType, ProtocolType protocolType)` ctor turn `DualMode` on.

**Comment by nibanks** [comment]
@tmds from a quick search of the Windows code it seems to be that the default is `IPV6_V6ONLY = 1`. It's hard coded that way as far as I can tell.

**Comment by tmds** [comment]
```cs
int port = 5004;

TcpListener listener = new TcpListener(new IPEndPoint(IPAddress.IPv6Any, port));
listener.Start();
Console.WriteLine($"Listening on IPv6Any:{port}");

using TcpClient clientIpv4 = new TcpClient();
var ipv4connect = clientIpv4.ConnectAsync(new IPEndPoint(IPAddress.Loopback, port)).ContinueWith(x =>
{
    Console.WriteLine("Connected via Ipv4 Loopback");
});

using TcpClient clientIpv6 = new TcpClient();
var ipv6connect = clientIpv6.ConnectAsync(new IPEndPoint(IPAddress.IPv6Loopback, port)).ContinueWith(x =>
{
    Console.WriteLine("Connected via Ipv6 Loopback");
});

await Task.WhenAll(ipv4connect, ipv6connect);
```

This code swallows the Task Exceptions.

If you change it to:
```cs
using System.Net;
using System.Net.Sockets;

int port = 5004;

TcpListener listener = new TcpListener(new IPEndPoint(IPAddress.IPv6Any, port));
listener.Start();
Console.WriteLine($"Listening on IPv6Any:{port}");

Console.WriteLine("Connecting via IPv6 Loopback:");
using TcpClient clientIpv6 = new TcpClient();
await clientIpv6.ConnectAsync(new IPEndPoint(IPAddress.IPv6Loopback, port));
Console.WriteLine("Connected via IPv6 Loopback");

Console.WriteLine("Connecting via IPv4 Loopback:");
using TcpClient clientIpv4 = new TcpClient();
await clientIpv4.ConnectAsync(new IPEndPoint(IPAddress.Loopback, port));
Console.WriteLine("Connected via IPv4 Loopback");
```

On Linux this gives:
```
Listening on IPv6Any:5004
Connecting via IPv6 Loopback:
Connected via IPv6 Loopback
Connecting via IPv4 Loopback:
Unhandled exception. System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at Program.<Main>$(String[] args) in /tmp/console/Program.cs:line 17
   at Program.<Main>(String[] args)
```

**Comment by nibanks** [comment]
Ah! Great find @tmds. So it is behaving as I'd expect, that IPv6 any only accepts IPv6 connections.
