### ISSUE TITLE
BugCheck in CxPlatSocketSendInternal (epoll)

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#2946]
### Describe the bug

Seen in a [recent CI run](https://dev.azure.com/ms/msquic/_build/results?buildId=343886&view=logs&j=0d6e46ad-e8ae-59ce-364c-b792f0422f2b&t=36b6355a-9880-572c-2f7c-46de69c440d5):
```
==================================================================================
 quicinterop.5816.1659662245.core
==================================================================================
[Current thread is 1 (Thread 0x7f25f6ffe700 (LWP 5824))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f2607cc6859 in __GI_abort () at abort.c:79
#2  0x00007f260819159c in quic_bugcheck (File=0x7f26083485d8 "/home/vsts/work/1/s/src/platform/datapath_epoll.c", Line=2525, Expr=0x7f26083488e0 "pthread_mutex_lock(&(&SocketContext->PendingSendDataLock)->Mutex) == 0") at /home/vsts/work/1/s/src/platform/platform_posix.c:78
#3  0x00007f2608198074 in CxPlatSocketSendInternal (Socket=0x7f2535da5410, LocalAddress=0x7f2514093c44, RemoteAddress=0x7f2514093c28, SendData=<optimized out>, IsPendedSend=<optimized out>) at /home/vsts/work/1/s/src/platform/datapath_epoll.c:2525
#4  0x00007f260819869d in CxPlatSocketSend (Socket=<optimized out>, Route=<optimized out>, SendData=<optimized out>, IdealProcessor=<optimized out>) at /home/vsts/work/1/s/src/platform/datapath_epoll.c:2710
#5  0x00007f260814f8f1 in QuicBindingSend (Binding=0x7f2535da4a50, Route=<optimized out>, SendData=<optimized out>, BytesToSend=39, DatagramsToSend=DatagramsToSend@entry=1, IdealProcessor=<optimized out>) at /home/vsts/work/1/s/src/core/binding.c:1830
#6  0x00007f260818e4d5 in QuicPacketBuilderSendBatch (Builder=Builder@entry=0x7f25f6ffd720) at /home/vsts/work/1/s/src/core/packet_builder.c:1017
#7  0x00007f260818eb43 in QuicPacketBuilderFinalize (Builder=Builder@entry=0x7f25f6ffd720, FlushBatchedDatagrams=FlushBatchedDatagrams@entry=1 '\001') at /home/vsts/work/1/s/src/core/packet_builder.c:968
#8  0x00007f2608187054 in QuicSendPathChallenges (Send=Send@entry=0x7f2514094520) at /home/vsts/work/1/s/src/core/send.c:1049
#9  0x00007f2608187283 in QuicSendFlush (Send=Send@entry=0x7f2514094520) at /home/vsts/work/1/s/src/core/send.c:1139
#10 0x00007f2608163dd4 in QuicConnDrainOperations (Connection=Connection@entry=0x7f2514093a50) at /home/vsts/work/1/s/src/core/connection.c:7356
#11 0x00007f26081477b4 in QuicWorkerProcessConnection (Worker=Worker@entry=0x5562ee86a3c0, Connection=0x7f2514093a50, ThreadID=ThreadID@entry=5824, TimeNow=TimeNow@entry=0x7f25f6ffde98) at /home/vsts/work/1/s/src/core/worker.c:510
#12 0x00007f2608147e00 in QuicWorkerLoop (Context=Context@entry=0x5562ee86a3c0, TimeNow=TimeNow@entry=0x7f25f6ffde98, ThreadID=ThreadID@entry=5824) at /home/vsts/work/1/s/src/core/worker.c:668
#13 0x00007f2608148106 in QuicWorkerThread (Context=0x5562ee86a3c0) at /home/vsts/work/1/s/src/core/worker.c:733
#14 0x00007f2607e9e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007f2607dc3133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
bash: line 1:  5816 Aborted                 (core dumped) LSAN_OPTIONS=report_objects=1 ASAN_OPTIONS=disable_coredump=0:abort_on_error=1 UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1 /home/vsts/work/1/s/artifacts/bin/linux/x64_Release_openssl/quicinterop
```

### Affected OS

- [ ] All
- [ ] Windows Server 2022
- [ ] Windows 11, version 22H2
- [ ] Windows 11, version 21H2
- [ ] Windows Insider Preview (specify affected build below)
- [X] Ubuntu
- [ ] Debian
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Run quicinterop on Ubuntu.

### Expected behavior

It runs to completion.

### Actual outcome

It crashed.

### Additional details

Dump: https://dev.azure.com/ms/_apis/resources/Containers/17853475/logs?itemPath=logs%2Flinux%2Fx64_Release_openssl%2Fquicinterop%2F08.05.2022.01.17.15%2Fquicinterop.5816.1659662245.core (14 GB)

**Comment by wujin1989** [comment]
Hihi, has this issue been resolved?

**Comment by nibanks** [comment]
Not that I know of.
