### ISSUE TITLE
OpenSSL 3.1

### ISSUE THREAD

**Issue by ManickaP** [microsoft/msquic#3698]
### Describe the bug

The build scripts don't work with newer OpenSSL 3 versions

```
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "3.1.1")
CMake Error at submodules/CMakeLists.txt:349 (message):
  OpenSSL 3.0 not found, found 3.1.1
```

@wfurt

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Build msquic on Linux with OpenSSL newer than 3.0.*.

### Expected behavior

It will build.

### Actual outcome

Doesn't build.

### Additional details

Workaround is not to use system crypto.

**Comment by nibanks** [comment]
We don't explicitly specify a 3.0 dependency anywhere I know of. Our package just specifies `3` as the dependency. Also, [our system crypto tests](https://github.com/microsoft/msquic/blob/main/.github/workflows/bvt.yml) are testing exactly what you seem to be doing. We test Ubuntu 22.04 using our system crypto built against 3.1, which passes.

**Comment by ManickaP** [comment]
I think this is the culprit:
https://github.com/microsoft/msquic/blob/88f0269b6a681efd0487aabb0bb67047c4735128/submodules/CMakeLists.txt#L339-L353

**Comment by nibanks** [comment]
Ah, you're probably right. Is there anyway to just link to the MAJOR version only, instead of 3.0? Does this work @manickap?
```
set(EXPECTED_OPENSSL_VERSION 3) 
```

**Comment by nibanks** [comment]
cc @wfurt & @csujedihy

**Comment by wfurt** [comment]
From what I remember the problem was comparisons e.g. 3.x >= 1.1.1. But since 1.x is done now we can flip it.

**Comment by vindicatorr** [comment]
I'm just going to subscribe to this issue since https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3 (which I see referenced here: https://github.com/microsoft/msquic/discussions/2291) doesn't seem to be enough:
```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Server.Kestrel.Core.dll: 'Unable to bind an HTTP/3 endpoint. This could be because QUIC has not been configured using UseQuic, or the platform doesn't support QUIC or HTTP/3.'
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Main(String[] pArgs)
```

I'm on Arch Linux and snagged https://packages.microsoft.com/ubuntu/23.04/prod/pool/main/libm/libmsquic/, then ran `debtap` to convert the format, and `pacman` to install it.
My "platform [DOES] support QUIC or HTTP/3", as I've enabled `Quic` in my browser via `chrome://flags`, and tested it from cloudflare while looking at `protocol` in chrome's dev-tools.

I saw mention that the openssl fork is required, but I'm just assuming that's only for building it since in the .deb manifest, I see mention of `openssl`, but no specified "fork".

I was going to run the repo `test`, but I guess it's required to build the repo first, even though I already installed libmsquic.

**Comment by wfurt** [comment]
It is strange that you need OpenSSL 1.1 Starting with Ubuntu 22.04 MsQuic _should_ depend on OpenSSL 3. And that what Arch uses by default, right @vindicatorr? 

And yes, `ldd` is good friend -> note that `Quic` is trying to load `libmsquic.so.2`. (you would see that with LD_DEBUG=libs`) If in doubts you can always build simple app and check `QuicListener.IsSupported` to avoid all the Kestrel layers.

**Comment by vindicatorr** [comment]
> should depend on OpenSSL 3. And that what Arch uses by default

Correct:
```
$ pacman -Qi openssl
Name            : openssl
Version         : 3.1.2-1
```

**Comment by wfurt** [comment]
Could you grab binaries from https://packages.microsoft.com/ubuntu/22.04 and give it another try @vindicatorr? 
Also note that there is Arch linux package and it _seems_ to be updated to latest: https://aur.archlinux.org/packages/msquic

**Comment by vindicatorr** [comment]
Well that's interesting that 22 would be aligned with openssl-3 unlike ubuntu-v23 depending on 1.1...
Right off the bat, when running `ldd` on the lib before installing it (during `debtap` extraction), I see `libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f62e6164000)`.

The only thing I had to do was change the `libssl3` dependency in the manifest (during `debtap`) to `openssl` (or I could have chosen to `skip` for `Do you want to skip the above package for this upgrade`).
I didn't even need `lttng-ust`, so I uninstalled that and `openssl-1.1`, and it still worked. Thanks.

I'm not sure I'd be want to go with the `aur` release given that it's v2.2 (same as the .deb), but also downloads other sources in order to build it like `googletest`. I figure I'll just stick with the pre-built .deb.

**Comment by wfurt** [comment]
we should probably fix the publishing @nibanks - perhaps @CarnaViire can help as she gets more into packaging/publishing....? .NET only test on LTS releases at the moment and it will probably stay like this.
