### ISSUE TITLE
Linux TCP Crash during TcpDataServer UT

### ISSUE THREAD

**Issue by nibanks** [microsoft/msquic#3968]
### Describe the bug

```Warning: [11/22/2023 20:26:11] Core file(s) generated

warning: core file may not match specified executable file.
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
==================================================================================
 msquicplatformt.8541.1700684771.core
==================================================================================
[Current thread is 1 (Thread 0x7f9e3c7fe700 (LWP 8543))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f9e40f9e859 in __GI_abort () at abort.c:79
#2  0x000055c32699ee59 in quic_bugcheck (File=0x55c327255880 "/__w/msquic/msquic/src/platform/datapath_epoll.c", Line=1053, Expr=0x55c327256140 "Socket->Uninitialized") at /__w/msquic/msquic/src/platform/platform_posix.c:93
#3  0x000055c3269c7819 in CxPlatSocketRelease (Socket=0x61300000ffc0) at /__w/msquic/msquic/src/platform/datapath_epoll.c:1053
#4  0x000055c3269cb9b2 in CxPlatSocketContextUninitializeComplete (SocketContext=0x613000010020) at /__w/msquic/msquic/src/platform/datapath_epoll.c:1100
#5  0x000055c3269dc081 in DataPathProcessCqe (Cqe=0x7f9e3c7fdc50) at /__w/msquic/msquic/src/platform/datapath_epoll.c:2670
#6  0x000055c3269a6668 in CxPlatDataPathProcessCqe (Cqe=<optimized out>) at /__w/msquic/msquic/src/platform/datapath_linux.c:407
#7  0x000055c3269be243 in CxPlatProcessEvents (Worker=0x616000008a80, State=<optimized out>) at /__w/msquic/msquic/src/platform/platform_worker.c:454
#8  0x000055c3269be9cc in CxPlatWorkerThread (Context=0x616000008a80) at /__w/msquic/msquic/src/platform/platform_worker.c:4[97](https://github.com/microsoft/msquic/actions/runs/6962267458/job/18945871311?pr=3967#step:9:98)
#9  0x00007f9e41e4e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007f9e4[109](https://github.com/microsoft/msquic/actions/runs/6962267458/job/18945871311?pr=3967#step:9:110)b133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Error: [11/22/2023 20:26:12] DataPathTest/DataPathTest.TcpDataServer/6 failed (in 1.3789777 sec):
```

### Affected OS

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other (specify below)

### MsQuic version

main

### Steps taken to reproduce bug

Run unit tests

### Expected behavior

Tests pass

### Actual outcome

Crash

### Additional details

https://github.com/microsoft/msquic/actions/runs/6962267458/job/18945871311?pr=3967

**Comment by nibanks** [comment]
I think this has been fixed.
