### ISSUE TITLE
Leak in QuicConnInitialize on WSL

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#419]
When running spinquic in WSL 2 with asan enabled, many objects initialized in QuicConnInitialize get leaked. Can only reproduce on WSL 2, both CI and a slow 8 year old AMD laptop pass without any leaks.

```
Direct leak of 99144 byte(s) in 729 object(s) allocated from:
    #0 0x7f01236c2b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f0122deb968 in QuicAlloc /home/thad/msquic/src/platform/platform_linux.c:111
    #2 0x7f0122d6feae in QuicPacketSpaceInitialize /home/thad/msquic/src/core/packet_space.c:26
    #3 0x7f0122d2a70a in QuicConnInitialize /home/thad/msquic/src/core/connection.c:265
    #4 0x7f0122d1ce13 in QuicBindingCreateConnection /home/thad/msquic/src/core/binding.c:1122
    #5 0x7f0122d1e489 in QuicBindingDeliverDatagrams /home/thad/msquic/src/core/binding.c:1364
    #6 0x7f0122d1ef66 in QuicBindingReceive /home/thad/msquic/src/core/binding.c:1506
    #7 0x7f0122d96336 in QuicSocketContextRecvComplete /home/thad/msquic/src/platform/datapath_linux.c:1235
    #8 0x7f0122d9accf in QuicSocketContextProcessEvents /home/thad/msquic/src/platform/datapath_linux.c:1467
    #9 0x7f0122d9b218 in QuicDataPathWorkerThread /home/thad/msquic/src/platform/datapath_linux.c:2205
    #10 0x7f0121de96da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Direct leak of 31104 byte(s) in 243 object(s) allocated from:
    #0 0x7f01236c2b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f0122deb968 in QuicAlloc /home/thad/msquic/src/platform/platform_linux.c:111
    #2 0x7f0122d71c38 in QuicRangeInitialize /home/thad/msquic/src/core/range.c:28
    #3 0x7f0122d2a728 in QuicConnInitialize /home/thad/msquic/src/core/connection.c:280
    #4 0x7f0122d1ce13 in QuicBindingCreateConnection /home/thad/msquic/src/core/binding.c:1122
    #5 0x7f0122d1e489 in QuicBindingDeliverDatagrams /home/thad/msquic/src/core/binding.c:1364
    #6 0x7f0122d1ef66 in QuicBindingReceive /home/thad/msquic/src/core/binding.c:1506
    #7 0x7f0122d96336 in QuicSocketContextRecvComplete /home/thad/msquic/src/platform/datapath_linux.c:1235
    #8 0x7f0122d9accf in QuicSocketContextProcessEvents /home/thad/msquic/src/platform/datapath_linux.c:1467
    #9 0x7f0122d9b218 in QuicDataPathWorkerThread /home/thad/msquic/src/platform/datapath_linux.c:2205
    #10 0x7f0121de96da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Indirect leak of 93312 byte(s) in 729 object(s) allocated from:
    #0 0x7f01236c2b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f0122deb968 in QuicAlloc /home/thad/msquic/src/platform/platform_linux.c:111
    #2 0x7f0122d71c38 in QuicRangeInitialize /home/thad/msquic/src/core/range.c:28
    #3 0x7f0122d877d1 in QuicAckTrackerInitialize /home/thad/msquic/src/core/ack_tracker.c:63
    #4 0x7f0122d6ff0a in QuicPacketSpaceInitialize /home/thad/msquic/src/core/packet_space.c:41
    #5 0x7f0122d2a70a in QuicConnInitialize /home/thad/msquic/src/core/connection.c:265
    #6 0x7f0122d1ce13 in QuicBindingCreateConnection /home/thad/msquic/src/core/binding.c:1122
    #7 0x7f0122d1e489 in QuicBindingDeliverDatagrams /home/thad/msquic/src/core/binding.c:1364
    #8 0x7f0122d1ef66 in QuicBindingReceive /home/thad/msquic/src/core/binding.c:1506
    #9 0x7f0122d96336 in QuicSocketContextRecvComplete /home/thad/msquic/src/platform/datapath_linux.c:1235
    #10 0x7f0122d9accf in QuicSocketContextProcessEvents /home/thad/msquic/src/platform/datapath_linux.c:1467
    #11 0x7f0122d9b218 in QuicDataPathWorkerThread /home/thad/msquic/src/platform/datapath_linux.c:2205
    #12 0x7f0121de96da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Indirect leak of 93312 byte(s) in 729 object(s) allocated from:
    #0 0x7f01236c2b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f0122deb968 in QuicAlloc /home/thad/msquic/src/platform/platform_linux.c:111
    #2 0x7f0122d71c38 in QuicRangeInitialize /home/thad/msquic/src/core/range.c:28
    #3 0x7f0122d877a0 in QuicAckTrackerInitialize /home/thad/msquic/src/core/ack_tracker.c:55
    #4 0x7f0122d6ff0a in QuicPacketSpaceInitialize /home/thad/msquic/src/core/packet_space.c:41
    #5 0x7f0122d2a70a in QuicConnInitialize /home/thad/msquic/src/core/connection.c:265
    #6 0x7f0122d1ce13 in QuicBindingCreateConnection /home/thad/msquic/src/core/binding.c:1122
    #7 0x7f0122d1e489 in QuicBindingDeliverDatagrams /home/thad/msquic/src/core/binding.c:1364
    #8 0x7f0122d1ef66 in QuicBindingReceive /home/thad/msquic/src/core/binding.c:1506
    #9 0x7f0122d96336 in QuicSocketContextRecvComplete /home/thad/msquic/src/platform/datapath_linux.c:1235
    #10 0x7f0122d9accf in QuicSocketContextProcessEvents /home/thad/msquic/src/platform/datapath_linux.c:1467
    #11 0x7f0122d9b218 in QuicDataPathWorkerThread /home/thad/msquic/src/platform/datapath_linux.c:2205
    #12 0x7f0121de96da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
```

**Comment by ThadHouse** [comment]
This was WSL specific. I can't reproduce it anymore. Digging around, it looks like https://github.com/microsoft/WSL2-Linux-Kernel/pull/53 might have fixed ASAN, as its linked from the original WSL1 ASAN bug.
