### ISSUE TITLE
Assertion in QuicSentFlush on Linux

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/msquic#427]
### Describe the bug

An assertion for empty framing logic is hit in QuicSentFlush. Might be related to #425 but could be separate. Hit in the spinquic tests

https://microsoft.visualstudio.com/OS/_build/results?buildId=23930069&view=results

```
#1  0x00007f6639ac0801 in __GI_abort () at abort.c:79
#2  0x00007f663aac6f2b in quic_bugcheck () at /home/vsts/work/1/s/src/platform/platform_linux.c:57
#3  0x00007f663aaaf94e in QuicSendFlush (Send=Send@entry=0x61d0018a17c0) at /home/vsts/work/1/s/src/core/send.c:1124
#4  0x00007f663aa801d3 in QuicConnDrainOperations (Connection=Connection@entry=0x61d0018a1080)
    at /home/vsts/work/1/s/src/core/connection.c:6106
#5  0x00007f663aa5d272 in QuicWorkerProcessConnection (Worker=Worker@entry=0x61e000000568,
    Connection=Connection@entry=0x61d0018a1080) at /home/vsts/work/1/s/src/core/worker.c:477
#6  0x00007f663aa5db21 in QuicWorkerThread (Context=0x61e000000568) at /home/vsts/work/1/s/src/core/worker.c:565
#7  0x00007f6639e786db in start_thread (arg=0x7f663426f700) at pthread_create.c:463
#8  0x00007f6639ba188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by nibanks** [comment]
I think this has been fixed some our one of recent fixes in this area. I haven't seen this since. Closing for now.
